name: dio_smart_retry
description: Retry library for Dio package made with love. By default, the request will be retried only for appropriate retryable http statuses.
version: 1.3.1
repository: https://github.com/rodion-m/dio_smart_retry
issue_tracker: https://github.com/rodion-m/dio_smart_retry/issues
homepage: https://github.com/rodion-m/dio_smart_retry
documentation: https://github.com/rodion-m/dio_smart_retry

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.6

dev_dependencies:
  dart_code_metrics: ^4.16.0
  test: ^1.21.4
  very_good_analysis: ^3.0.1
