name: dio_smart_retry
description: Retry library for Dio and Dio package made with love. By default, the request will be retried only for appropriate retryable http statuses.
version: 7.0.1
repository: https://github.com/rodion-m/dio_smart_retry
issue_tracker: https://github.com/rodion-m/dio_smart_retry/issues
homepage: https://github.com/rodion-m/dio_smart_retry
documentation: https://github.com/rodion-m/dio_smart_retry#contents

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.7.0
  http_parser: ^4.1.0
  path: ^1.9.0

dev_dependencies:
  dart_code_metrics: ^5.7.6
  test: ^1.25.8
  very_good_analysis: ^6.0.0
