name: dio_smart_retry
description: Retry library for Dio package made with love. By default, the request will be retried only for appropriate retryable http statuses.
version: 1.0.2
repository: https://github.com/rodion-m/dio_smart_retry
issue_tracker: https://github.com/rodion-m/dio_smart_retry/issues
homepage: https://github.com/rodion-m/dio_smart_retry
documentation: https://github.com/rodion-m/dio_smart_retry

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0

dev_dependencies:
  test: ^1.17.10
  very_good_analysis: ^2.2.0
  dart_code_metrics: ^4.1.0