name: dio_smart_retry
description: Retry library for Dio and Dio package made with love. By default, the request will be retried only for appropriate retryable http statuses.
version: 2.0.1
repository: https://github.com/rodion-m/dio_smart_retry
issue_tracker: https://github.com/rodion-m/dio_smart_retry/issues
homepage: https://github.com/rodion-m/dio_smart_retry
documentation: https://github.com/rodion-m/dio_smart_retry#contents

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^5.0.0
  http_parser: ^4.0.2
  path: ^1.8.2

dev_dependencies:
  dart_code_metrics: ^5.5.1
  test: ^1.23.1
  very_good_analysis: ^4.0.0+1
